[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
dapped_out = "7TGLYkGJFEx9JvHqWDzJKTkad6AfsBFWywPk9fXDF5yF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/basti/.config/solana/id.json"

[scripts]
test = "pnpm vitest run"

[test]
startup_wait = 15000
shutdown_wait = 2000
upgradeable = false
